version: '3'

services:
  frontend:
    image: ghcr.io/benlewsey27/react-weather:latest
    container_name: react-weather
    environment:
      - BACKEND_URL=react-weather-api:3001
      - RESOLVER_IP=127.0.0.11
    ports:
      - "8000:80"
    build: ./frontend

  backend:
    image: ghcr.io/benlewsey27/react-weather-api:latest
    container_name: react-weather-api
    environment:
      - WEATHER_API_KEY=$WEATHER_API_KEY
      - WEATHER_API_URL=http://react-weather-mock:3002/weather
    build: ./backend
  
  backendMock:
    image: ghcr.io/benlewsey27/react-weather-mock:latest
    container_name: react-weather-mock
    build: ./backend-mock
