---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-weather-api
  labels:
    app: react-weather-api
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: react-weather-api
  template:
    metadata:
      labels:
        app: react-weather-api
    spec:
      containers:
      - name: main
        image: {{ .Values.backend.image.registry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        env:
          {{- include "benlewsey27.backend-env-vars" . | indent 10 }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 4
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 2
          periodSeconds: 2
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: {{ .Values.backend.resources.requests.memory }}
            cpu: {{ .Values.backend.resources.requests.cpu }}
          limits:
            memory: {{ .Values.backend.resources.limits.memory }}
            cpu: {{ .Values.backend.resources.limits.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: react-weather-api
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 3001
