{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-weather
spec:
  ingressClassName: {{ .Values.frontend.ingress.ingressClass }}
  rules:
  - host: {{ .Values.frontend.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path:  {{ .Values.frontend.ingress.path }}
        backend:
          service:
            name: {{ .Values.frontend.service.name }}
            port:
              number: {{ .Values.frontend.service.port }}
{{- end }}
