apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-weather-frontend
  labels:
    app: react-weather-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-weather-frontend
  template:
    metadata:
      labels:
        app: react-weather-frontend
    spec:
      containers:
        - name: react-weather-frontend
          image: benlewsey27/react-weather-frontend:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-weather-frontend
spec:
  type: NodePort
  selector:
    app: react-weather-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80