frontend:
  replicas: 1
  image:
    registry: ghcr.io/benlewsey27
    repository: react-weather-frontend
    tag: latest
  service:
    name: react-weather-frontend
    type: ClusterIP
    port: 80
  env:
    BACKEND_URL: "{{ .Values.backend.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}"
    RESOLVER_IP: "kube-dns.kube-system.svc.cluster.local"

backend:
  replicas: 1
  image:
    registry: ghcr.io/benlewsey27
    repository: react-weather-backend
    tag: latest
  service:
    name: react-weather-backend
    type: ClusterIP
    port: 3001
  env:
    WEATHER_API_KEY: "XXXX"
