frontend:
  replicas: 1
  image:
    registry: ghcr.io/benlewsey27
    repository: react-weather
    tag: latest
  service:
    name: react-weather
    type: ClusterIP
    port: 80
  env:
    BACKEND_URL: "{{ .Values.backend.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}"
    RESOLVER_IP: "kube-dns.kube-system.svc.cluster.local"
  ingress:
    enabled: false
    ingressClass: nginx
    host: react-weather.example.com
    path: /

backend:
  replicas: 1
  image:
    registry: ghcr.io/benlewsey27
    repository: react-weather-api
    tag: latest
  service:
    name: react-weather-api
    type: ClusterIP
    port: 3001
  env:
    WEATHER_API_KEY: "XXXX"
